Squashed commit of the following:
    ESDK-3419 ESDKC Websocket Transport Support - Implementation

    ESDK-3676 rsslWebSocketGetBuffer() should return
	RSSL_RET_BUFFER_NO_BUFFERS when used buffers max has been
	exceeded

       This was an issue seen while adding a feature to ProvPerf.  It
       should be reproduced by using a ProvPerf not built with this fix
       and prior to the jira ESDK-3654, which added WebSocket support
       for JSON conversion.

    ESDK-3654 ProvPerf/ConsPerf: add WebSocket and encrypted WebSocket
	connection support

        This commit enables ProvPerf with/without '-reactor' option,
        to accept both rssl.rwf and rssljson.v2(tr_json2) connections.
        Until the changes for ConsPerf are finished, VAConsumer can be used
        to verify these connection.
        ./ProvPerf -maxFragmentSize 64440 -pl "rssl.json.v2 rssl.rwf"
    	    and
        ./VAConsumer -pl <[rssl.json.v2 | rssl.rwf]> -webSocket localhost:14002 DIRECT_FEED
        mp:TRI

    ESDK-3643 WS Server side transport should optionally reject open HS
	requests at the transport level

        If RsslBindOptions .wsOpts.protocols is not defined
        then any new WS open requests will be rejected by the server within
        the transport read header processing (ipcProcessHdr())

    ESDK-3619 Please provide QA the way to monitor Websocket Handshake
	fields
    	This required a change to the RCDEV cmake file
    	rcdevCompilerOptions.cmake to ensure any command line or
    	precache options for RCDEV_EXTRA_ flags are set for every source
    	repo build.  In order to see the change when building with
    	RCDEV, a new pull from rcdev / master should be done

    ESDK-3633 Update VAProvider and VAConsumer examples for webSocket
	connection

        -pl is the webSocket sub-protocol list

        Examples for running apps:
        ./VAProvider -p 14002 -s DIRECT_FEED -id 1 -pl "rssl.rwf"

        ./VAConsumer -pl "rssl.rwf" -webSocket localhost:14002 DIRECT_FEED mp:TRI

        For encryption replace '-encrypted' with:
        ./VAConsumer -pl "rssl.rwf, rssl.json.v2" -encryptedWebSocket

    ESDK-3635 Add RWF/JSON Converter support within the Reactor

        Initial changes for Reactor support

    ESDK-3475 ESDK C: RWF<->JSON conversion open sourcing

        Full feature added to esdk minus 1 unit test case not passing

    ESDK-3613 rsslTransportTest Client WS subprotocol 'json' core dumps
	with compressionType=1, compression Level=any, when client
	sends msg size 6145 to server

    ESDK-3611 Client subprotocol 'json' gets 'Zlib error: -3'
	with compressionType=1, compression Level=0, when Server
	sends message size 6145
    	This Jira was addressed in part since there is no current
    	support for writing fragmented WS frames with JSON protocol.
    	However, writing fragmented RWF data is supported. So, since
    	this test case is JSON2 protocol and the requested data size is
    	greater than the max fragment size, the proper behavior is for
    	an error to be generated on the server side when the fragment
    	size is entered/ or a requested buffer of a size greater than
    	the max fragment. This is the part which needs to be added.

    	The new error text returned is:
    	Error: 0010 rsslSocketGetBuffer() Cannot get a buffer larger
    	than maximum message size for JSON protocol session.

    ESDK-3610 rsslTransportTest websocket Session Info displays
    	CompressionType:0 even when compressionType set to 1
    ESDK-3601 rsslTransportTest core dump when Server sends
    	fragmented buffer to client subprotocol rssl.json.v2 and
    	then session shutdown.

    ESDK-3605 Client Keynonce starting with '/' are not
    	parsed correctly within http hanshakes

Author of following jiras: soranat.thiarachow <soranat.thiarachow@refinitiv.com>
    ESDK-3688 Fixed ExtendedLine connectionType Segmentation fault (core
	  dumped) both Server and Client when client connected.

    ESDK-3685 Fixed the conversion library not to use the default service
	  ID for login domain.

    ESDK-3684 Fixed the conversion library not to set
	  RSSL_RQMF_MSG_KEY_IN_UPDATES by default for Login and Dictionary
	  domains.

    ESDK-3683 Turned off adding a QoS range on requests that doesn't specify
	  a QoS. Added the catchUnknownJsonKeys and catchUnknownJsonFids
	  options.

    ESDK-3674 Modified the NIProvider and Provider to send
	  RSSL_MPEA_DELETE_ENTRY action after others actions for mbp and
	  mbo
        - Modified the VANIProvider and VAProvider to send
	  RSSL_MPEA_DELETE_ENTRY action after others actions for mbp and
	  mbo

    ESDK-3675 Fixed VAConsumer does not exit when it fails to convert
	  JSON to RWF and runtime expires.

    ESDK-3647 Fixed the transport library to send websocket open hand
	  shake request after the proxy connection is established.

    ESDK-3645 Modifed VAConsumer to provide a callback method to map from
	  service name to service ID which is required for the
	  conversion library

    ESDK-3644 Provided a configuration parameter to define the maximum
	  message size on client side for WebSocket protocol in the 
	  RsslWSocketOpts

    ESDK-3655 Fixed VAConsumer to support posting message with enumerated
	  values

    ESDK-3628 Cleaned up error handling for open handshake request by
	  client and sending hand shake response by server.
	- Cleaned up TODO in the rwsReadOpeningHandshake() method
	  and use the rwsDataBuffer() to get a buffer for the
	  rwsSendWsPing(), rwsSendWsPong() and rwsSendWsClose() methods.
	- Overrided the RsslTransportChannelFuncs.channelClose function
	  pointer with the rsslWebSocketCloseChannel() method to send
	  close frame before closing the socket channel.
	- Fixed the rwsSendWsPing, rwsSendWsPong, and rwsSendWsClose
	  method to send valid websocket frame.
	- Fixed the rsslWebSocketPing method to send JSON ping message
	  with the [{"Type":"Ping"}] format as same as ADS.
	- Calls the rsslSetJsonWebSocketFunctions() function only when
	  the websocket subprotocols has been neogiated.
	- Fixed rwsSendPingData() to specify payload length when writing
	  websocket header to send payload data properly.
	- Added mutext lock in the rwsDataBuffer() method to synchronize
	  multi-threaded access

    ESDK-3629 Fixed Client app does NOT send json format when
	  connType=Encrypted, Encrypted Protocol=ws,
	  subprotocol=rssl.json2 / tr_json2

    ESDK-3630 Fixed to properly free message buffer and set its length
	  when sending WS close, pong, ping frame.

    ESDK-3627 Fixed ETA generates incorrect accepted key for WebSocket
	  handshake by using REAL_SHA1_INT and 20 bytes of the SHA1
	  digest value.

    ESDK-3620 Fixed to set the RsslSocketChannel.protocolFuncs to the
	  RSSL_CONN_TYPE_SOCKET type for encrypted connection for
	  server and client. Fixed to properly create encrypted connection
	  for WebSocket connection.

    ESDK-3603 Fixed Server gets error when sending fragmented buffer>
	  maxFragmentedSize, client connectionType:TCP gets only one
	  fragmented data and then disconnected.

    ESDK-3602 Added hanlding for sending large JSON message on web
	  socket frame
	- Fixed the rsslSocketRead() and rsslWebSocketRead() to return
	  the actual bytes read from network via the
	  RsslReadOutArgs.bytesRead member.

    ESDK-3649 Fixed CMake build to build the librssl_shared library
	  with the REAL_SHA1_INIT predefined as same as the static version

    ESDK-3641 Fixed There is always '1 bytes pending to be flushed' when
	  rsslTransportTest Server/Client sends message via websocket json

    ESDK-3640 Fixed rwsSendPingData() method to compress the JSON PING
	  message as well when the RSSL_COMP_ZLIB compression type is
	  enabled.

    ESDK-3419 ESDKC Websocket Transport Support - Implementation
	- Updated the CMakeLists.txt for librsslJsonConverter to support
	  the BUILD_WITH_PREBUILT_ETA_EMA_LIBRARIES config for the GSG
	  package.
	- Fixed build errors from rsslJsonConverterTest with Visual
	  Studio 2012.
	- Set default value for the RSSL_JSON_CPC_ALLOW_ENUM_DISPLAY_STRINGS
	  properly to RSSL_TRUE so that the JSON converter can handle
	  instead of resulting in the decode errror
	- Added error handling to ensure that the JSON converter library
	  has been initialized properly.
	- Fixed the Reactor to properly format the error message when it
	  fails to convert from RWF to JSON protocol.
	- Fixed rwsSendWsClose() method to properly unlock the mutex
	  properly to avoid deadlock.
	- Changed the size of RsslWSocketOpts.maxMsgSize from
	  RsslUInt32 to RsslUInt64
	- Fixed rwsReadWebSocket() to limit the maximum read size to the
	  RsslSocketChannel.readSize parameter so that it has additional
	  buffer to read more data from network.
	- Created memory to hold dictionary list in rsslInitRJConverter().
	- Modifed rsslReactorSubmit() to copy converted RWF message from
	  JSON before calling rsslWrite().
	- Fixed rsslWebSocketCloseChannel() to send WS close frame only
	  when the Channel is still active.
	- Fixed rwsWriteWebSocket() to set the return value from calling
	  the rwsWriteAndFlush() method.
	- Fixed the synchronization lock in the rwsSendPingData().
	- Fixed VAConsumer to set the sub-protocols for
	  the -encryptedWebSocket option as well
	- Fixed rwsReadTransportMsg() to read only the remaining data to
	  complete websocket frame's payload.
	- Added checking to advanced the input cursor only once per frame.
	- Fixed for server side to support multiple protocols by updating
	  the RsslTransChannelFuncs member vairable of rsslChannelImpl
	  using the rsslGetTransportChannelFunc() instead of overriding
	  every function pointers with the rsslSetJsonWebSocketFunctions
	  method.
	- Advanced the inputBufCursor of RsslSocketChannel after passing
	  the WS frame header.
	- Fixed to handle HTTP error status codes properly from the
	  WebSocket openhandshake response.
	- Added additional handling for Provider applications to send
	  JSON ping message then he client applications replys with JSON
	  PONG message.
	- Added implementation to send JSON ERROR back when the converter
	  failed to convert JSON message due to format/semantic errors.
	- Cleaning up debugging messages in the Reactor, VAProvider and
	  VAConsumer.
	- Additional implementation to callback to provider application
	  to map from service name to ID needed. Added a callback method
	  to VAProvider to perform the mapping from service name to ID.
	- Provided the RsslReactorJsonConverterOptions structure to
	  specify a RsslDataDictionary, a default service ID, and service
	  name to ID callback method.
	- Added librsslJsonConverter as a dependency of librsslVA_shared
	  for Linux platform.
	- Fixed librsslJsonConverter_shared to use the RSSL_RJC_API macro
	  for creating DLL for Windows. Added librsslJsonConverter as a
	  depencenty of librsslVA_shared.

    Author: Sukanda Thanakijlurskool <sukanda.thanakijlurskool@refinitiv.com>
	VAProvider and VAConsumer QATools
	    modified:   qa_readme.txt
	    new file:   vaconsumer-Ws-001/files
	    new file:   vaconsumer-Ws-001/rsslConsumer.c
	    new file:   vaconsumer-Ws-001/rsslConsumer.h
	    new file:   vaprovider-Ws-001/files
	    new file:   vaprovider-Ws-001/rsslItemHandler.c
	    new file:   vaprovider-Ws-001/rsslItemHandler.h
	    new file:   vaprovider-Ws-001/rsslProvider.c

    Author: Mitchell Kato <mitchell.kato@refinitiv.com>
	    TREP-2667: Fix real display issue and some other misc fixes